blank_issues_enabled: true
contact_links:
  - name: Add new MyToDo
    about: made by config.yml
    # edit {username} and {repo} for your environment
    url: https://github.com/mayuyuyuyunn/MyToDo/issues/new?template=custom.md&projects=mayuyuyuyunn%2FMyToDo%2F9&labels=MyToDo&assignees=mayuyuyuyunn
